services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'mydatabase'
      TZ: Asia/Seoul
    ports:
      - '3306:3306'
